# Generated by Django 4.2.16 on 2024-12-13 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления - 1 мин. !'), django.core.validators.MaxValueValidator(1000, message='Максимальное время приготовления - 1000 мин. !')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество - 1 !'), django.core.validators.MaxValueValidator(10000, message='Максимальное количество - 10000 !')], verbose_name='Количество'),
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
