# Generated by Django 4.2.16 on 2024-12-13 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Никнейм содержит запрещенные символы! Пожалуйста, используйте только буквы, цифры и символы .@+-', regex='^[\\w.@+-]+$')], verbose_name='Никнейм'),
        ),
    ]
